#!/bin/sh
set -eu
PATH=/usr/sbin:/usr/bin:/sbin:/bin
export PATH
[ "$(id -u)" = 0 ] && [ "$#" = 1 ] || exit 1
case "$1" in
    suspend)
        [ -w /sys/power/state ] && grep -qw mem /sys/power/state || exit 1
        sync
        printf 'mem\n' > /sys/power/state ;;
    reboot) exec /sbin/reboot ;;
    poweroff) exec /sbin/poweroff ;;
    *) exit 1 ;;
esac
